
sudo: required

language: cpp

services:
  - docker

before_install:
  - docker pull ubuntu:latest;
  - docker run -d --name ubuntu -dti ubuntu:latest bash;
  - docker ps -a;
  - docker exec ubuntu mkdir /STL;
  - docker cp . ubuntu:/STL;
  - docker exec ubuntu apt-get update;
  - docker exec ubuntu apt-get -y upgrade;
  - docker exec ubuntu apt-get -y install sudo build-essential cmake curl;

script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - docker exec ubuntu /bin/bash -c 'cd /STL; cmake .'
  - docker exec ubuntu /bin/bash -c 'cd /STL; cmake --build .'
  - docker exec ubuntu /bin/bash -c 'cd /STL; ctest'
  - docker exec ubuntu curl -u travis:Aachen123 -T /STL/Testing/Temporary/CTestCostData.txt "https://owncloud.schlien.me/owncloud/remote.php/dav/files/travis/logs/CTestCostData.txt"
  - docker exec ubuntu curl -u travis:Aachen123 -T /STL/Testing/Temporary/LastTestsFailed.log "https://owncloud.schlien.me/owncloud/remote.php/dav/files/travis/logs/LastTestsFailed.log"
  - docker exec ubuntu curl -u travis:Aachen123 -T /STL/Testing/Temporary/LastTest.log "https://owncloud.schlien.me/owncloud/remote.php/dav/files/travis/logs/LastTest.log"

